-module(stone_token).
-export([to_string/1, from_string/1]).

%% Single-byte token → string
to_string(16#01) -> <<"message">>;
to_string(16#02) -> <<"from">>;
to_string(16#03) -> <<"to">>;
to_string(16#04) -> <<"cmd">>;
to_string(16#05) -> <<"id">>;
to_string(16#06) -> <<"@s.im">>;
to_string(16#07) -> <<"@g.im">>;
to_string(16#08) -> <<"type">>;
to_string(16#09) -> <<"body">>;
to_string(16#0A) -> <<"chat">>;
to_string(16#0B) -> <<"receipt">>;
to_string(16#0C) -> <<"read">>;
to_string(16#0D) -> <<"presence">>;
to_string(16#0E) -> <<"ping">>;
to_string(16#0F) -> <<"pong">>;
to_string(16#10) -> <<"s.im">>;
to_string(16#11) -> <<"g.im">>;
to_string(16#12) -> <<"hello">>;
to_string(16#13) -> <<"hello_ack">>;
to_string(16#14) -> <<"version">>;
to_string(16#15) -> <<"cap">>;
to_string(16#16) -> <<"name">>;
to_string(16#17) -> <<"session">>;
to_string(16#18) -> <<"client">>;
to_string(16#19) -> <<"device">>;
to_string(16#1A) -> <<"auth">>;
to_string(16#1B) -> <<"auth_ok">>;
to_string(16#1C) -> <<"auth_fail">>;
to_string(16#1D) -> <<"user">>;
to_string(16#1E) -> <<"token">>;
to_string(16#1F) -> <<"last_seq">>;
to_string(16#20) -> <<"seq">>;
to_string(16#21) -> <<"ack">>;
to_string(16#22) -> <<"nack">>;
to_string(16#23) -> <<"retry">>;
to_string(16#24) -> <<"attempt">>;
to_string(16#25) -> <<"offline_pull">>;
to_string(16#26) -> <<"offline_batch">>;
to_string(16#27) -> <<"after_seq">>;
to_string(16#28) -> <<"limit">>;
to_string(16#29) -> <<"more">>;
to_string(16#2A) -> <<"error">>;
to_string(16#2B) -> <<"code">>;
to_string(16#2C) -> <<"detail">>;
to_string(16#2D) -> <<"min_version">>;
to_string(16#2E) -> <<"max_version">>;
to_string(_)     -> undefined.

%% string → single-byte token (reverse lookup)
from_string(<<"message">>)        -> {ok, 16#01};
from_string(<<"from">>)           -> {ok, 16#02};
from_string(<<"to">>)             -> {ok, 16#03};
from_string(<<"cmd">>)            -> {ok, 16#04};
from_string(<<"id">>)             -> {ok, 16#05};
from_string(<<"@s.im">>)          -> {ok, 16#06};
from_string(<<"@g.im">>)          -> {ok, 16#07};
from_string(<<"type">>)           -> {ok, 16#08};
from_string(<<"body">>)           -> {ok, 16#09};
from_string(<<"chat">>)           -> {ok, 16#0A};
from_string(<<"receipt">>)        -> {ok, 16#0B};
from_string(<<"read">>)           -> {ok, 16#0C};
from_string(<<"presence">>)       -> {ok, 16#0D};
from_string(<<"ping">>)           -> {ok, 16#0E};
from_string(<<"pong">>)           -> {ok, 16#0F};
from_string(<<"s.im">>)           -> {ok, 16#10};
from_string(<<"g.im">>)           -> {ok, 16#11};
from_string(<<"hello">>)          -> {ok, 16#12};
from_string(<<"hello_ack">>)      -> {ok, 16#13};
from_string(<<"version">>)        -> {ok, 16#14};
from_string(<<"cap">>)            -> {ok, 16#15};
from_string(<<"name">>)           -> {ok, 16#16};
from_string(<<"session">>)        -> {ok, 16#17};
from_string(<<"client">>)         -> {ok, 16#18};
from_string(<<"device">>)         -> {ok, 16#19};
from_string(<<"auth">>)           -> {ok, 16#1A};
from_string(<<"auth_ok">>)        -> {ok, 16#1B};
from_string(<<"auth_fail">>)      -> {ok, 16#1C};
from_string(<<"user">>)           -> {ok, 16#1D};
from_string(<<"token">>)          -> {ok, 16#1E};
from_string(<<"last_seq">>)       -> {ok, 16#1F};
from_string(<<"seq">>)            -> {ok, 16#20};
from_string(<<"ack">>)            -> {ok, 16#21};
from_string(<<"nack">>)           -> {ok, 16#22};
from_string(<<"retry">>)          -> {ok, 16#23};
from_string(<<"attempt">>)        -> {ok, 16#24};
from_string(<<"offline_pull">>)   -> {ok, 16#25};
from_string(<<"offline_batch">>)  -> {ok, 16#26};
from_string(<<"after_seq">>)      -> {ok, 16#27};
from_string(<<"limit">>)          -> {ok, 16#28};
from_string(<<"more">>)           -> {ok, 16#29};
from_string(<<"error">>)          -> {ok, 16#2A};
from_string(<<"code">>)           -> {ok, 16#2B};
from_string(<<"detail">>)         -> {ok, 16#2C};
from_string(<<"min_version">>)    -> {ok, 16#2D};
from_string(<<"max_version">>)    -> {ok, 16#2E};
from_string(_)                    -> not_found.
